[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "ldap"
    version = "@project.version@"
    path = "../ldap-native/build/libs/ldap-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["ldap"]
