[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "ldap"
    version = "@project.version@"
    path = "../ldap-native/build/libs/ldap-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["ldap"]

    [[platform.libraries]]
    artifactId = "apacheds-all"
    version = "2.0.0-M24"
    path = "./lib/apacheds-all-2.0.0-M24.jar"
    groupId = "org.apache.directory.server"
    modules = ["ldap"]
